### ISSUE TITLE
Logging should be removed

### ISSUE THREAD

**Issue by Sapvier** [HaidaiAndrii/arrayMethods#9]
https://github.com/HaidaiAndrii/arrayMethods/blob/a2391095a308d335361bbc9c43aacd7bb0fcc715/MyArray/script.js#L105
https://github.com/HaidaiAndrii/arrayMethods/blob/a2391095a308d335361bbc9c43aacd7bb0fcc715/MyArray/script.js#L106
https://github.com/HaidaiAndrii/arrayMethods/blob/a2391095a308d335361bbc9c43aacd7bb0fcc715/MyArray/script.js#L107

**Comment by HaidaiAndrii** [comment]
removed
